name: Deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copying files
      run: |
        cp src/repository/user/serviceTwo/model.mongo.ts src/repository/user/serviceTwo/model.ts
        cp src/repository/user/serviceTwo/model.graphql.ts src/repository/user/serviceTwo/model.graphql.ts

    # Insert the necessary deployment steps for your GraphQL service
    - name: Deployment
      run: |
        cd ./
        npm install
